services:
  go-backend:
    extends:
      file: ./go-server/docker-compose.yml
      service: go-backend

  documents-service:
    extends:
      file: ./services/documents-service/docker-compose.yml
      service: documents-service

  zookeeper:
    extends:
      file: ./zookeeper.yml
      service: zookeeper

  kafka:
    extends:
      file: ./kafka.yml
      service: kafka

volumes:
  go-mod-cache:
  go-build-cache:
