export enum ErrorCodes {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  FORM_ERROR = 'FORM_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  MISSING_FIELD = 'MISSING_FIELD',
  INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
  PASSWORD_WEAK = 'PASSWORD_WEAK',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_LOCKED = 'RESOURCE_LOCKED',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  LLM_ERROR = 'LLM_ERROR',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  RESOURCE_CREATION_ERROR = 'RESOURCE_CREATION_ERROR',
  LATEX_ERROR = 'LATEX_ERROR',
  NOT_FOUND = "NOT_FOUND"
}

export interface ApiError {
  status: number;
  message: string;
  errorCode: string;
  timestamp: string;
  details?: string;
}